export const senators = 
  [ 
    { party: 'Republican',
      first_name: 'Lamar',
      last_name: 'Alexander',
      state_abv: 'TN',
      state_name: 'Tennessee' },
    { party: 'Republican',
      first_name: 'Susan',
      last_name: 'Collins',
      state_abv: 'ME',
      state_name: 'Maine' },
    { party: 'Republican',
      first_name: 'John',
      last_name: 'Cornyn',
      state_abv: 'TX',
      state_name: 'Texas' },
    { party: 'Democrat',
      first_name: 'Richard',
      last_name: 'Durbin',
      state_abv: 'IL',
      state_name: 'Illinois' },
    { party: 'Republican',
      first_name: 'Michael',
      last_name: 'Enzi',
      state_abv: 'WY',
      state_name: 'Wyoming' },
    { party: 'Republican',
      first_name: 'Lindsey',
      last_name: 'Graham',
      state_abv: 'SC',
      state_name: 'South Carolina' },
    { party: 'Republican',
      first_name: 'James',
      last_name: 'Inhofe',
      state_abv: 'OK',
      state_name: 'Oklahoma' },
    { party: 'Republican',
      first_name: 'Mitch',
      last_name: 'McConnell',
      state_abv: 'KY',
      state_name: 'Kentucky' },
    { party: 'Democrat',
      first_name: 'John',
      last_name: 'Reed',
      state_abv: 'RI',
      state_name: 'Rhode Island' },
    { party: 'Republican',
      first_name: 'Pat',
      last_name: 'Roberts',
      state_abv: 'KS',
      state_name: 'Kansas' },
    { party: 'Republican',
      first_name: 'Shelley',
      last_name: 'Capito',
      state_abv: 'WV',
      state_name: 'West Virginia' },
    { party: 'Democrat',
      first_name: 'Edward',
      last_name: 'Markey',
      state_abv: 'MA',
      state_name: 'Massachusetts' },
    { party: 'Democrat',
      first_name: 'Tom',
      last_name: 'Udall',
      state_abv: 'NM',
      state_name: 'New Mexico' },
    { party: 'Republican',
      first_name: 'Bill',
      last_name: 'Cassidy',
      state_abv: 'LA',
      state_name: 'Louisiana' },
    { party: 'Democrat',
      first_name: 'Gary',
      last_name: 'Peters',
      state_abv: 'MI',
      state_name: 'Michigan' },
    { party: 'Democrat',
      first_name: 'Mark',
      last_name: 'Warner',
      state_abv: 'VA',
      state_name: 'Virginia' },
    { party: 'Republican',
      first_name: 'James',
      last_name: 'Risch',
      state_abv: 'ID',
      state_name: 'Idaho' },
    { party: 'Democrat',
      first_name: 'Jeanne',
      last_name: 'Shaheen',
      state_abv: 'NH',
      state_name: 'New Hampshire' },
    { party: 'Democrat',
      first_name: 'Jeff',
      last_name: 'Merkley',
      state_abv: 'OR',
      state_name: 'Oregon' },
    { party: 'Democrat',
      first_name: 'Chris',
      last_name: 'Coons',
      state_abv: 'DE',
      state_name: 'Delaware' },
    { party: 'Republican',
      first_name: 'Cory',
      last_name: 'Gardner',
      state_abv: 'CO',
      state_name: 'Colorado' },
    { party: 'Republican',
      first_name: 'Tom',
      last_name: 'Cotton',
      state_abv: 'AR',
      state_name: 'Arkansas' },
    { party: 'Republican',
      first_name: 'Steve',
      last_name: 'Daines',
      state_abv: 'MT',
      state_name: 'Montana' },
    { party: 'Democrat',
      first_name: 'Cory',
      last_name: 'Booker',
      state_abv: 'NJ',
      state_name: 'New Jersey' },
    { party: 'Republican',
      first_name: 'Dan',
      last_name: 'Sullivan',
      state_abv: 'AK',
      state_name: 'Alaska' },
    { party: 'Republican',
      first_name: 'David',
      last_name: 'Perdue',
      state_abv: 'GA',
      state_name: 'Georgia' },
    { party: 'Republican',
      first_name: 'Joni',
      last_name: 'Ernst',
      state_abv: 'IA',
      state_name: 'Iowa' },
    { party: 'Republican',
      first_name: 'Thom',
      last_name: 'Tillis',
      state_abv: 'NC',
      state_name: 'North Carolina' },
    { party: 'Republican',
      first_name: 'Mike',
      last_name: 'Rounds',
      state_abv: 'SD',
      state_name: 'South Dakota' },
    { party: 'Republican',
      first_name: 'Benjamin',
      last_name: 'Sasse',
      state_abv: 'NE',
      state_name: 'Nebraska' },
    { party: 'Republican',
      first_name: 'Michael',
      last_name: 'Crapo',
      state_abv: 'ID',
      state_name: 'Idaho' },
    { party: 'Republican',
      first_name: 'Charles',
      last_name: 'Grassley',
      state_abv: 'IA',
      state_name: 'Iowa' },
    { party: 'Democrat',
      first_name: 'Patrick',
      last_name: 'Leahy',
      state_abv: 'VT',
      state_name: 'Vermont' },
    { party: 'Republican',
      first_name: 'Lisa',
      last_name: 'Murkowski',
      state_abv: 'AK',
      state_name: 'Alaska' },
    { party: 'Democrat',
      first_name: 'Patty',
      last_name: 'Murray',
      state_abv: 'WA',
      state_name: 'Washington' },
    { party: 'Democrat',
      first_name: 'Charles',
      last_name: 'Schumer',
      state_abv: 'NY',
      state_name: 'New York' },
    { party: 'Republican',
      first_name: 'Richard',
      last_name: 'Shelby',
      state_abv: 'AL',
      state_name: 'Alabama' },
    { party: 'Democrat',
      first_name: 'Ron',
      last_name: 'Wyden',
      state_abv: 'OR',
      state_name: 'Oregon' },
    { party: 'Republican',
      first_name: 'Roy',
      last_name: 'Blunt',
      state_abv: 'MO',
      state_name: 'Missouri' },
    { party: 'Republican',
      first_name: 'John',
      last_name: 'Boozman',
      state_abv: 'AR',
      state_name: 'Arkansas' },
    { party: 'Republican',
      first_name: 'Richard',
      last_name: 'Burr',
      state_abv: 'NC',
      state_name: 'North Carolina' },
    { party: 'Republican',
      first_name: 'John',
      last_name: 'Isakson',
      state_abv: 'GA',
      state_name: 'Georgia' },
    { party: 'Republican',
      first_name: 'Jerry',
      last_name: 'Moran',
      state_abv: 'KS',
      state_name: 'Kansas' },
    { party: 'Republican',
      first_name: 'Robert',
      last_name: 'Portman',
      state_abv: 'OH',
      state_name: 'Ohio' },
    { party: 'Republican',
      first_name: 'Patrick',
      last_name: 'Toomey',
      state_abv: 'PA',
      state_name: 'Pennsylvania' },
    { party: 'Democrat',
      first_name: 'Chris',
      last_name: 'Van Hollen',
      state_abv: 'MD',
      state_name: 'Maryland' },
    { party: 'Republican',
      first_name: 'John',
      last_name: 'Thune',
      state_abv: 'SD',
      state_name: 'South Dakota' },
    { party: 'Democrat',
      first_name: 'Michael',
      last_name: 'Bennet',
      state_abv: 'CO',
      state_name: 'Colorado' },
    { party: 'Republican',
      first_name: 'Todd',
      last_name: 'Young',
      state_abv: 'IN',
      state_name: 'Indiana' },
    { party: 'Republican',
      first_name: 'James',
      last_name: 'Lankford',
      state_abv: 'OK',
      state_name: 'Oklahoma' },
    { party: 'Republican',
      first_name: 'Tim',
      last_name: 'Scott',
      state_abv: 'SC',
      state_name: 'South Carolina' },
    { party: 'Democrat',
      first_name: 'Richard',
      last_name: 'Blumenthal',
      state_abv: 'CT',
      state_name: 'Connecticut' },
    { party: 'Republican',
      first_name: 'Marco',
      last_name: 'Rubio',
      state_abv: 'FL',
      state_name: 'Florida' },
    { party: 'Republican',
      first_name: 'Rand',
      last_name: 'Paul',
      state_abv: 'KY',
      state_name: 'Kentucky' },
    { party: 'Republican',
      first_name: 'John',
      last_name: 'Hoeven',
      state_abv: 'ND',
      state_name: 'North Dakota' },
    { party: 'Republican',
      first_name: 'Mike',
      last_name: 'Lee',
      state_abv: 'UT',
      state_name: 'Utah' },
    { party: 'Republican',
      first_name: 'Ron',
      last_name: 'Johnson',
      state_abv: 'WI',
      state_name: 'Wisconsin' },
    { party: 'Democrat',
      first_name: 'Brian',
      last_name: 'Schatz',
      state_abv: 'HI',
      state_name: 'Hawaii' },
    { party: 'Democrat',
      first_name: 'Tammy',
      last_name: 'Duckworth',
      state_abv: 'IL',
      state_name: 'Illinois' },
    { party: 'Democrat',
      first_name: 'Kamala',
      last_name: 'Harris',
      state_abv: 'CA',
      state_name: 'California' },
    { party: 'Republican',
      first_name: 'John',
      last_name: 'Kennedy',
      state_abv: 'LA',
      state_name: 'Louisiana' },
    { party: 'Democrat',
      first_name: 'Margaret',
      last_name: 'Hassan',
      state_abv: 'NH',
      state_name: 'New Hampshire' },
    { party: 'Democrat',
      first_name: 'Catherine',
      last_name: 'Cortez Masto',
      state_abv: 'NV',
      state_name: 'Nevada' },
    { party: 'Democrat',
      first_name: 'Doug',
      last_name: 'Jones',
      state_abv: 'AL',
      state_name: 'Alabama' },
    { party: 'Democrat',
      first_name: 'Tina',
      last_name: 'Smith',
      state_abv: 'MN',
      state_name: 'Minnesota' },
    { party: 'Republican',
      first_name: 'Cindy',
      last_name: 'Hyde-Smith',
      state_abv: 'MS',
      state_name: 'Mississippi' },
    { party: 'Democrat',
      first_name: 'Maria',
      last_name: 'Cantwell',
      state_abv: 'WA',
      state_name: 'Washington' },
    { party: 'Democrat',
      first_name: 'Thomas',
      last_name: 'Carper',
      state_abv: 'DE',
      state_name: 'Delaware' },
    { party: 'Democrat',
      first_name: 'Dianne',
      last_name: 'Feinstein',
      state_abv: 'CA',
      state_name: 'California' },
    { party: 'Democrat',
      first_name: 'Debbie',
      last_name: 'Stabenow',
      state_abv: 'MI',
      state_name: 'Michigan' },
    { party: 'Democrat',
      first_name: 'Tammy',
      last_name: 'Baldwin',
      state_abv: 'WI',
      state_name: 'Wisconsin' },
    { party: 'Republican',
      first_name: 'Marsha',
      last_name: 'Blackburn',
      state_abv: 'TN',
      state_name: 'Tennessee' },
    { party: 'Democrat',
      first_name: 'Sherrod',
      last_name: 'Brown',
      state_abv: 'OH',
      state_name: 'Ohio' },
    { party: 'Democrat',
      first_name: 'Benjamin',
      last_name: 'Cardin',
      state_abv: 'MD',
      state_name: 'Maryland' },
    { party: 'Democrat',
      first_name: 'Robert',
      last_name: 'Menendez',
      state_abv: 'NJ',
      state_name: 'New Jersey' },
    { party: 'Independent',
      first_name: 'Bernard',
      last_name: 'Sanders',
      state_abv: 'VT',
      state_name: 'Vermont' },
    { party: 'Republican',
      first_name: 'Roger',
      last_name: 'Wicker',
      state_abv: 'MS',
      state_name: 'Mississippi' },
    { party: 'Democrat',
      first_name: 'Christopher',
      last_name: 'Murphy',
      state_abv: 'CT',
      state_name: 'Connecticut' },
    { party: 'Democrat',
      first_name: 'Mazie',
      last_name: 'Hirono',
      state_abv: 'HI',
      state_name: 'Hawaii' },
    { party: 'Democrat',
      first_name: 'Kirsten',
      last_name: 'Gillibrand',
      state_abv: 'NY',
      state_name: 'New York' },
    { party: 'Democrat',
      first_name: 'Amy',
      last_name: 'Klobuchar',
      state_abv: 'MN',
      state_name: 'Minnesota' },
    { party: 'Democrat',
      first_name: 'Jon',
      last_name: 'Tester',
      state_abv: 'MT',
      state_name: 'Montana' },
    { party: 'Democrat',
      first_name: 'Robert',
      last_name: 'Casey',
      state_abv: 'PA',
      state_name: 'Pennsylvania' },
    { party: 'Democrat',
      first_name: 'Sheldon',
      last_name: 'Whitehouse',
      state_abv: 'RI',
      state_name: 'Rhode Island' },
    { party: 'Republican',
      first_name: 'John',
      last_name: 'Barrasso',
      state_abv: 'WY',
      state_name: 'Wyoming' },
    { party: 'Democrat',
      first_name: 'Martin',
      last_name: 'Heinrich',
      state_abv: 'NM',
      state_name: 'New Mexico' },
    { party: 'Democrat',
      first_name: 'Joe',
      last_name: 'Manchin',
      state_abv: 'WV',
      state_name: 'West Virginia' },
    { party: 'Democrat',
      first_name: 'Kyrsten',
      last_name: 'Sinema',
      state_abv: 'AZ',
      state_name: 'Arizona' },
    { party: 'Democrat',
      first_name: 'Elizabeth',
      last_name: 'Warren',
      state_abv: 'MA',
      state_name: 'Massachusetts' },
    { party: 'Independent',
      first_name: 'Angus',
      last_name: 'King',
      state_abv: 'ME',
      state_name: 'Maine' },
    { party: 'Republican',
      first_name: 'Kevin',
      last_name: 'Cramer',
      state_abv: 'ND',
      state_name: 'North Dakota' },
    { party: 'Republican',
      first_name: 'Deb',
      last_name: 'Fischer',
      state_abv: 'NE',
      state_name: 'Nebraska' },
    { party: 'Republican',
      first_name: 'Ted',
      last_name: 'Cruz',
      state_abv: 'TX',
      state_name: 'Texas' },
    { party: 'Democrat',
      first_name: 'Timothy',
      last_name: 'Kaine',
      state_abv: 'VA',
      state_name: 'Virginia' },
    { party: 'Republican',
      first_name: 'Martha',
      last_name: 'McSally',
      state_abv: 'AZ',
      state_name: 'Arizona' },
    { party: 'Democrat',
      first_name: 'Jacky',
      last_name: 'Rosen',
      state_abv: 'NV',
      state_name: 'Nevada' },
    { party: 'Republican',
      first_name: 'Rick',
      last_name: 'Scott',
      state_abv: 'FL',
      state_name: 'Florida' },
    { party: 'Republican',
      first_name: 'Mike',
      last_name: 'Braun',
      state_abv: 'IN',
      state_name: 'Indiana' },
    { party: 'Republican',
      first_name: 'Joshua',
      last_name: 'Hawley',
      state_abv: 'MO',
      state_name: 'Missouri' },
    { party: 'Republican',
      first_name: 'Mitt',
      last_name: 'Romney',
      state_abv: 'UT',
      state_name: 'Utah' }
  ]

// const result = senators.map(senator => {
//     const obj = {}
//     obj.party = senator.party
//     obj.first_name = senator.person.firstname
//     obj.last_name = senator.person.lastname
//     obj.state_abv = senator.state
//     obj.state_name = senator.description.split(' ').slice(3).join(' ')
//     return obj
// });


// console.log(result)