const states = 
  [ 
    { abreviation: 'TN',
      name: 'Tennessee' },
    { abreviation: 'ME',
      name: 'Maine' },
    { abreviation: 'TX',
      name: 'Texas' },
    { abreviation: 'IL',
      name: 'Illinois' },
    { abreviation: 'WY',
      name: 'Wyoming' },
    { abreviation: 'SC',
      name: 'South Carolina' },
    { abreviation: 'OK',
      name: 'Oklahoma' },
    { abreviation: 'KY',
      name: 'Kentucky' },
    { abreviation: 'RI',
      name: 'Rhode Island' },
    { abreviation: 'KS',
      name: 'Kansas' },
    { abreviation: 'WV',
      name: 'West Virginia' },
    { abreviation: 'MA',
      name: 'Massachusetts' },
    { abreviation: 'NM',
      name: 'New Mexico' },
    { abreviation: 'LA',
      name: 'Louisiana' },
    { abreviation: 'MI',
      name: 'Michigan' },
    { abreviation: 'VA',
      name: 'Virginia' },
    { abreviation: 'ID',
      name: 'Idaho' },
    { abreviation: 'NH',
      name: 'New Hampshire' },
    { abreviation: 'OR',
      name: 'Oregon' },
    { abreviation: 'DE',
      name: 'Delaware' },
    { abreviation: 'CO',
      name: 'Colorado' },
    { abreviation: 'AR',
      name: 'Arkansas' },
    { abreviation: 'MT',
      name: 'Montana' },
    { abreviation: 'NJ',
      name: 'New Jersey' },
    { abreviation: 'AK',
      name: 'Alaska' },
    { abreviation: 'GA',
      name: 'Georgia' },
    { abreviation: 'IA',
      name: 'Iowa' },
    { abreviation: 'NC',
      name: 'North Carolina' },
    { abreviation: 'SD',
      name: 'South Dakota' },
    { abreviation: 'NE',
      name: 'Nebraska' },
    { abreviation: 'VT',
      name: 'Vermont' },
    { abreviation: 'WA',
      name: 'Washington' },
    { abreviation: 'NY',
      name: 'New York' },
    { abreviation: 'AL',
      name: 'Alabama' },
    { abreviation: 'MO',
      name: 'Missouri' },
    { abreviation: 'OH',
      name: 'Ohio' },
    { abreviation: 'PA',
      name: 'Pennsylvania' },
    { abreviation: 'MD',
      name: 'Maryland' },
    { abreviation: 'IN',
      name: 'Indiana' },
    { abreviation: 'CT',
      name: 'Connecticut' },
    { abreviation: 'FL',
      name: 'Florida' },
    { abreviation: 'ND',
      name: 'North Dakota' },
    { abreviation: 'UT',
      name: 'Utah' },
    { abreviation: 'WI',
      name: 'Wisconsin' },
    { abreviation: 'HI',
      name: 'Hawaii' },
    { abreviation: 'CA',
      name: 'California' },
    { abreviation: 'NV',
      name: 'Nevada' },
    { abreviation: 'MN',
      name: 'Minnesota' },
    { abreviation: 'MS',
      name: 'Mississippi' },
    { abreviation: 'AZ',
      name: 'Arizona' }
  ]

  module.exports = states;